config/routes.rb
Tourism::Application.routes.draw do
  get "welcome/index"

  root :to => 'welcome#index'
  resources "entries"
  

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :contents, :date, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

def index
	@entries = Entry.all
end

def show
    @entry = Entry.find(params["id"])
end

def create
entry_params = params["entry"]
entry = Entry.create(entry_params)
redirect_to(entry_path(entry))
end

def edit
@entry = Entry.find(params["id"])
end

def update
entry_params = params["entry"]
entry = Entry.find(params["id"])
entry.update_attributes(entry_params)
redirect_to(entry_path(entry))
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

@entries = Entry.all

@website1 = [
["http://www.kohlipethailand.com/", "Koh Lipe, Thailand"],
]

@website2 = [
["http://www.namibiatourism.com.na/", "Namibia, Africa"],
]

@website3 = [
["http://www.cuscoperu.com/en/", "Cusco, Peru"],
]

@website4 = [
["https://www.travelbelize.org/","Belize, Central America"],
]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/edit.html.erb
<%= form_for(@entry) do |form| %>
<p><%= form.label("title") %></p>
<p><%= form.text_field("title") %></p>
<p><%= form.label("date") %></p>
<p><%= form.text_field("date") %></p>
<p><%= form.label("contents") %></p>
<p><%= form.text_area("contents") %></p>
<p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to this entry", entry_path(@entry)) %></p>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/index.html.erb
<h1 style="color: green; font-size: 30px; font-family: 'Arial', Arial, serif;">DESTINATION NEWS</h1>

<% for entry in @entries %>
<h2 style="font-size: 20px; font-family: 'Times New Roman', Times, serif;"><%= link_to(entry.title, entry_path(entry)) %></h2>
<p style="color: grey; font-size: 12px; font-family: 'Times New Roman', Times, serif;"><%= entry.date %></p>
<p style="font-size: 14px; font-family: 'Times New Roman', Times, serif;"><%= entry.contents %></p>
<% end %>

<%= link_to("New entry", new_entry_path) %>
<p><%= link_to("Main Page", welcome_index_path) %>

app/views/entries/new.html.erb
<%= form_for(Entry.new) do |form| %>
<p><%= form.label("title") %></p>
<p><%= form.text_field("title") %></p>
<p><%= form.label("date") %></p>
<p><%= form.text_field("date") %></p>
<p><%= form.label("contents") %></p>
<p><%= form.text_area("contents") %></p>
<p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/show.html.erb
<h2 style="color: green; font-size: 20px; font-family: 'Times New Roman', Times, serif;"><%= @entry.title %></h2>
 <p style="color: grey; font-size: 12px; font-family: 'Times New Roman', Times, serif;"><%= @entry.date %></p>
 <p style="font-size: 14px; font-family: 'Times New Roman', Times, serif;"><%= @entry.contents %></p> 	 

 <p><%= link_to("Edit this entry", edit_entry_path(@entry)) %></p>

 <p><%= link_to("Back to all entries", entries_path) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tourism</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<center><h1><p style="color: green; font-size: 40px; font-family: 'Arial'">Go Sustainable Tourism</h1></center>
<center><p style="color: grey; font-family: 'Arial'"> Brings you to the most sustainable tourism destinations in the world!</p></center>

<center><b><p style="color: purple; font-size: 30px; font-family: 'Arial'">*FEATURED DESTINATIONS*</p></b></center>


<div style="float:left; display:block; width:500px; height: 260px">
	
<% for url, name in @website1 %>
<b><a href="<%= url %>"><p style="color: #04B486; font-size: 20px; font-family: 'Arial'"><%= name %></p></a></b>
<% end %>

<img src="http://www.oceanprodivers.net/wp-content/uploads/2012/07/koh_lipe.jpg" /width=400 height=150>
</div> 


<div style="float:right; display:block; width:500px; height: 260px">

<% for url, name in @website2 %>
<b><a href="<%= url %>"><p style="color: #FE9A2E; font-size: 20px; font-family: 'Arial'"><%= name %></p></a></b>
<% end %>    
     

<img src="http://www.holidaybazaar.travel/wp-content/uploads/2014/05/namibia.jpg" /width=400 height=150>
</div>


<div style="float:left; display:block; width:500px; height: 260px">
    
<% for url, name in @website3 %>
<b><a href="<%= url %>"><p style="color: #7B5F0C; font-size: 20px; font-family: 'Arial'"><%= name %></p></a></b>
<% end %>

<img src="http://www.globeholidays.net/South_America/Peru/Media/Cusco_Machu_Picchu_Peru.jpg" /width=400 height=150>
</div>


<div style="float:right; display:block;width:500px; height: 260px">
    
<% for url, name in @website4 %>
<b><a href="<%= url %>"><p style="color: #013ADF; font-size: 20px; font-family: 'Arial'"><%= name %></p></a></b>
<% end %>

<img src="http://www.abercrombiekent.co.uk/_assets/images/belize/belize.jpg" /width=400 height=150>
</div>


<center><h1><p style="color: purple; font-size: 30px; font-family: 'Arial'"><%= link_to("*DESTINATION NEWS*", entries_path) %></p><h1></center>


<% for entry in @entries %>
<h2 style="color: green; font-size: 20px; font-family: 'Times New Roman', Times, serif;"><%= entry.title %></h2>
<p style="color: grey; font-size: 12px; font-family: 'Times New Roman', Times, serif;"><%= entry.date %></p>
<p style="font-size: 14px; font-family: 'Times New Roman', Times, serif;"><%= entry.contents %></p>
<% end %>


<center><p style="color: grey; font-size: 10px; font-family: 'Arial'">Web Creator: Chenyan Lu</center>